### ISSUE TITLE
this repo should be part of the semaphore org.. 

### ISSUE THREAD

**Issue by steadfasterX** [semaphoreui/semaphore-docs#10]
**imho** this repo should be part of https://github.com/ansible-semaphore

as already described for the snap repo ( https://github.com/fiftin/ansible-semaphore-snap/issues/1 )

moving this repo to the ansible-semaphore organisation would :

* makes it easier for users/devs to find this repo
*  you'll have everything belonging together in one place 
* makes it easier to work on it when the project grows (organisation / team permissions etc)

**Comment by tboerger** [comment]
All relevant repositories are part of the same organization now.
