### ISSUE TITLE
Is it possible to configure separate Runners for each project in Semaphore?

### ISSUE THREAD

**Issue by mariiko-dev** [semaphoreui/semaphore-docs#55]
I would like to know if it's possible in the current version of Semaphore to set up separate Runners for different projects, where each project has its own dedicated infrastructure. For example:

- Project "local" should be associated with one infrastructure and a dedicated Runner.
- Project "remote zero trust" should be associated with another infrastructure and a separate Runner.

The goal is for all projects to be accessible through a single Semaphore UI, where selecting a project would automatically choose the appropriate Runner based on its configuration.

Question:
Is it possible in the current version of Semaphore to configure separate Runners for different projects and have the UI automatically select the corresponding Runner when a project is chosen?

**Comment by fiftin** [comment]
Hi @mariiko-dev it is possible in Premium version.
